### ISSUE TITLE
Not participating flag not respected when Randomizing

### ISSUE THREAD

**Issue by TravelingGeek** [thepaperpilot/Gift-Exchange-2#4] opened 2016-10-22 03:41 UTC
Anthony is not participating, but was included in the draw

**Comment by thepaperpilot** [comment] 2016-11-07 02:32
I'm having issues reproducing the issue. Can you explain what you did, what you expected to happen, and what happened instead?

**Comment by TravelingGeek** [comment] 2016-11-07 02:56
I'll try to repoduce this

**Comment by thepaperpilot** [comment] 2016-11-07 04:33
There was an issue where when a person had no potential gift recipients that fit all the rules, it wouldn't be assigned a recipient at all, and was fixed in 8f39578dfc830115b7ce2701c75cb2c85ee33b95. That _might_ have been the issue you're describing, but it didn't concern the participating boolean (which I still can't reproduce any faults in), and was making people effectively not participate when they should be, as opposed to the other way around.

**Comment by thepaperpilot** [comment] 2016-11-21 01:13
The issue you're describing might also have been the issue I fixed in 1a82fda35b53a88b14fee9c66fb15baf2be8580c.

Between the two bugs I fixed I'm going to assume the issue has been resolved.

**Closed as completed by thepaperpilot** 2016-11-21 01:13 UTC

**Comment by TravelingGeek** [comment] 2016-11-21 01:41
Ok
